# Generated by Django 3.2.6 on 2021-08-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='created',
        ),
    ]
