# Generated by Django 3.2.6 on 2021-08-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0002_remove_stockhistory_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='export_to_CSV',
        ),
    ]
