# Generated by Django 3.2.6 on 2021-08-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0003_remove_stockhistory_export_to_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='export_to_CSV',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
