# Generated by Django 3.2.6 on 2021-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0004_alter_stock_export_to_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
        migrations.AddField(
            model_name='stock',
            name='csv',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
